# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hornet',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hornet',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hornet',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hornet',
            name='view_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
