# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20160925_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='hornet',
            name='name',
            field=models.CharField(default='New test post', max_length=200),
        ),
        migrations.AddField(
            model_name='hornetnode',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hornetnode',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hornetnode',
            name='name',
            field=models.CharField(default='New test post', max_length=200),
        ),
    ]
