# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-27 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20160927_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hornet',
            old_name='pub_date',
            new_name='pub_dtime',
        ),
        migrations.RenameField(
            model_name='hornet',
            old_name='view_datetime',
            new_name='view_dtime',
        ),
    ]
