# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20160927_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hornet',
            name='email',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
