# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-27 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20160927_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='hornet',
            name='ip',
            field=models.CharField(default='Noip', max_length=200),
        ),
    ]
